### PR TITLE
Ruby 2.4

### PR DESCRIPTION
**Pull request by timbreitkreutz**
Upgrade quack gem to work with currently supported ruby versions: 2.2, 2.3, 2.4

It was a bit tricky getting this to work without any deprecation warnings and without doing any monkeying around with internal types...

### CODE REVIEW

**Comment by timbreitkreutz** [comment]
Ready for review @djreimer

**Comment by timbreitkreutz** [comment]
ping @djreimer

**Comment by derrickreimer** [comment]
@timbreitkreutz is this backwards compatible with older rubies?

**Comment by timbreitkreutz** [comment]
I only tested it on 2.2, 2.3, and 2.4 (which were the currently supported Ruby versions when I did this)-- did you want to test other versions?

**Comment by derrickreimer** [comment]
No that's fine with me 👍

**Comment by derrickreimer** [comment]
@timbreitkreutz v1.0 released

**Comment by timbreitkreutz** [comment]
Thx!

**Pull request merged**
